import = ["~/.config/alacritty/cyberdream.toml"]

[scrolling]
history = 5000

[font]
# normal = { family = "Jetbrains Nerdfont Mono", style = "Regular" }
# for 4k
size = 15
# for 4k with 125 scale
# size = 12.5
# for 4k with 150 scale aka 2k
# size = 11.25
# size = 10.75

# [colors]
# [colors.primary]
# foreground = "#52ad70"
# background = "#000000"
# background = "0x282828"
# foreground = "0xebdbb2"

[window]
opacity = 0.8
decorations = "none"
